manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: gpeye
      url-base: https://github.com/GPeye
    - name: tokyo2006
      url-base: https://github.com/tokyo2006
    - name: englmaxi
      url-base: https://github.com/englmaxi

  projects:
    - name: hammerbeam-slideshow
      remote: gpeye
      revision: main 
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0s  
      import: app/west.yml

    # Add ZMK modules from configuration 1
    - name: zmk-adaptive-key
      remote: zmkfirmware
      path: modules/zmk/adaptive-key
    - name: zmk-auto-layer
      remote: zmkfirmware
      path: modules/zmk/auto-layer
    - name: zmk-helpers
      remote: zmkfirmware
      path: modules/zmk/helpers
    - name: zmk-leader-key
      remote: zmkfirmware
      path: modules/zmk/leader-key
    - name: zmk-tri-state
      remote: zmkfirmware
      path: modules/zmk/tri-state
    - name: zmk-unicode
      remote: zmkfirmware
      path: modules/zmk/unicode
      
    - name: zephyr
      remote: zmkfirmware
      revision: v3.5.0+zmk-fixes

    - name: prospector-zmk-module
      remote: tokyo2006
      revision: change_spi2
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main

  self:
    path: config
